sonyxperiadev/device-sony-shinano

- rootdir/init.shinano.rc
> shinano : Start mlog_qmi_service on boot

- BoardConfig.mk
switch to out/...../dts folder to be able to use dtb files for both inline and
prebuilt kernels
Signed-off-by: Aleksi Suomalainen <suomalainen.aleksi@gmail.com>
> mkqcdtimage: use dts from out folder

- BoardConfig.mk
This is just wrong, and hardcoded paths are always bad.
If anything, this should use $(OUT_DIR), or the proper kernel paths as needed.
> Revert "mkqcdtimage: use dts from out folder"

- rootdir/init.shinano.rc
Include bcmdhd overlay configurations for (wpa/p2p)_supplicant and
modify both services' parameters to use those configurations
> WiFi: Make it working for 3.10

- rootdir/init.shinano.pwr.rc
- rootdir/init.shinano.rc
While this may be good when booting the system, it's actually really
bad for kernel. Remove lines that will mess with the I/O scheduler
and its configuration to follow kernel defaults.
> [SHINANO] init: Remove I/O scheduler changes. Follow kernel defaults.

- device.mk
- rootdir/init.shinano.rc
**device.mk**:
Add timekeep to product packages
(Tested and working, but does it need both timekeep and TimeKeep? )
**rootdir/init.shinano.rc**:
Add timekeep service and remove old directory
( Tested and working )
[ https://github.com/galaxyfreak/device-sony-yukon/commit/8156b05f858eb5e1e8867c7caf5247e366dca928#commitcomment-10121183 ]
Commit by galaxyfreak 
Comment on product packages by jerpelea
> Add timekeep fix for time persistence

- BoardConfig.mk
BOARD_USES_GENERIC_AUDIO is obsolete https://android.googlesource.com/platform/hardware/libhardware_legacy/+/android-5.0.2_r1/audio/Android.mk
> Remove BOARD_USES_GENERIC_AUDIO

- rootdir/init.shinano.rc
Reverts sonyxperiadev/device-sony-shinano#43
It *should* not be world readable, as it contains the IMEI and serial number.
> Revert "shinano: fix cmdline permission"

- BoardConfig.mk
See AOSP devices is TARGET_BOARD_PLATFORM := instead TARGET_BOARD_PLATFORM =
https://android.googlesource.com/device/asus/fugu/+/android-5.1.0_r1/BoardConfig.mk string 30
https://android.googlesource.com/device/asus/flo/+/android-5.1.0_r1/BoardConfigCommon.mk string 46
> shinano: Fix typo

- device.mk
Sirius, Castor, Leo, Aries and Scorpion are calling: aosp_base.mk
telephony.mk
in AOSP telephony.mk is calling (Dialer): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/telephony.mk
in AOSP aosp_base.mk calls others .mk as core.mk who is calling (Email and Exchange2) (Strings 35 and 36): https://android.googlesource.com/platform/build/+/android-5.1.0_r3/target/product/core.mk
> shinano: remove overrides packages

- BoardConfig.mk
AOSP uses shinano not shinano-common
> Fix directory name to shinano not shinano-common

- system.prop
These values are not defined by AOSP as dalvik-heap but these are needed by all shinano devices for set HWUI memory limits
These values can be founded in bruild.prop (Sony Stock) by all shinano devices
> shinano: Set HWUI memory limits props

- overlay/packages/services/Telephony/res/values/config.xml
This is set false by default in AOSP. see (string 54): https://android.googlesource.com/platform/packages/services/Telephony/+/android-5.1.1_r1/res/values/config.xml
> shinano: remove override world phone overlay

- device.mk
AOSP builds is ignoring our audio_effects.conf at the start of build.
Correct the paths instead of system/etc/audio_effects.conf ---> system/vendor/etc/audio_effects.conf as hammerhead
See (string 170): https://android.googlesource.com/device/lge/hammerhead/+/android-5.1.1_r1/device.mk
> shinano: copy audio_effects to correct way

- rootdir/fstab.shinano
logcat:
```
W/DirectVolume(  272): Deprecated implied prefix pattern detected, please use '/devices/msm_sdcc.2/mmc_host*' instead
```
>  fstab: Update syntax for external sdcard 

- BoardConfig.mk
Currently, the FrameBuffer in AOSP is double-buffering.
That's bad in cases when Compositor takes time near 16ms or less.
There're so many blockers('WaitForever') in several composition periods which makes janks. While we make it triple-buffering, those blockers disappear
> shinano: set Num of surface buffers to 3

- rootdir/init.shinano.pwr.rc
the correct path is /dev/cpuctl/cpu.notify_on_migrate not /dev/cpuctl/apps/cpu.notify_on_migrate
> shinano: Fix path to cpuctl

- rootdir/init.shinano.rc
- rootdir/ueventd.shinano.rc
deleted not exist format_3d: ls -l /sys/class/graphics/fb1/format_3d: No such file or directory
Add missing chown system graphics /sys/class/graphics/fb1/video_mode (init.shinano.rc)
Add missing /sys/devices/virtual/graphics/fb1/hdcp/tp (ueventd.shinano.rc)
> shinano: ramdisk: fix for video nodes

- device.mk
remove uneeded cdma permission (isn't needed due to not any target of shinano family is a cdma device)
Added missing sensors permissions: Stepdetector
Stepcounter
Light
Proximity
Compass
Accelerometer
> shinano: Update permissions

- rootdir/init.shinano.rc
- rootdir/ueventd.shinano.rc
E/qdhwcomposer(  255): void qhwc::adWrite(const int&): Failed to open /sys/class/graphics/fb2/ad with error Permission denied
> shinano: avoid fb2 denials

- rootdir/init.shinano.rc
Launch QMUXD as root to enable it to obtain AP_BLOCK_SUSPEND
capability to acquire wakelock during suspend.
QMUXD will downgrade itself to user radio after getting the
necessary capabilities.
fix:
E/QC-QMI  (  396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI  (  396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI  (  396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI  (  396): linux_qmi_qmux_io_wake_unlock: Err in writing wakelock=qmuxd_port_wl_0, error [1:Operation not permitted]
E/QC-QMI  (  396): linux_qmi_qmux_io_wake_lock: Err in writing wakelock=qmuxd_port_wl_0, error …
> shinano: init: qmux: Launch QMUXD process as root user

- rootdir/init.shinano.rc
- rootdir/ueventd.shinano.rc
also, remove reprecated entries.
> shinano: init: Assign bluetooth DUN port-bridge to bt stack group

- rootdir/init.shinano.rc
- rootdir/ueventd.shinano.rc
add some permissions for files/devices that are still
present at 3.10-BF64 kernel
these entries are present on shinano leo at least
> shinano: init: add missed permissions

- liblights/lights.c
This is required for devices which have panels with integrated
backlight controller, usable with commands sent through MDSS.
> [Scorpion BUGFIX] liblights: Cleanup and fix for MDSS DSI CMDs-driven backlight

- BoardConfig.mk
This is needed in case sooner or later the default will change.
> [Shinano] BoardConfig: Specify not to build any bootloader

- rootdir/system/etc/audio_policy.conf
Following hammerhead and (rhine - yukon)
> shinano: fix inputs for usb and submix

- rootdir/system/etc/audio_effects.conf
actually in vendor/sony/qcom/prebuilt/proprietary/vendor/lib/soundfx we have 3 blobs provided by Sony (libqcbassboost.so, libqcreverb.so, libqcvirt.so) those are required by:
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L104
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L105
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L107
so adding them to audio_effects.conf for make them work
> shinano: use proper qcom audio_effects

- rootdir/init.shinano.rc
The operating system can detect when an application is reading
data sequentially from a file or from disk.
In such cases, it performs an intelligent read-ahead algorithm,
whereby more data than is requested by the user is read from disk.
Thus, when the user next attempts to read a block of data, it will
already by in the operating system's page cache.
The potential down side to this is that the operating system can
read more data from disk than necessary, which occupies space in
the page cache until it is evicted because of high memory pressure.
Having multiple processes doing false read-ahead would increase
memory pressure in this circumstance.
So, this change reduces read_ahead_kb value from 2048 to 512 then
this setting tells the operating system not to read extra bytes,
which can …
> shinano: init: decrease read ahead buffer size

- rootdir/init.shinano.pwr.rc
those are defined by init.rc see: http://pastebin.com/wA6ANDe4 (strings 363 to 385)
> shinano: ramdisk: remove duplicated permissions to cpu

- system.prop
on this commit: https://github.com/sonyxperiadev/kernel/commit/20a6eb95259e965b9cfa72cb156ac3f384d2c39a // we can see as our actual kernel is using 0X8010 for black instead 0X8080 who is gray
aosp is using 0X8080 on actual android-5.1.1_r4 branch: https://android.googlesource.com/platform/hardware/qcom/media/+/android-5.1.1_r4/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp (see string 129)
so change actual 0X8080 black with that one used by our kernel who is 0X8010 via prop persist.vidc.dec.conceal_color // commit 960a885dd7112b852c183ba5cad699ee24ae3a05 for platform/hardware/qcom/media
> shinano: use proper black conceal color for our kernel 3.10

- Android.mk
- BoardConfig.mk
- rootdir/init.shinano.rc
- sepolicy/addrsetup.te
- sepolicy/device.te
- sepolicy/file.te
- sepolicy/file_contexts
- sepolicy/property.te
- sepolicy/property_contexts
- sepolicy/sct.te
- sepolicy/sensors.te
- sepolicy/service.te
- sepolicy/service_contexts
- sepolicy/system_app.te
- sepolicy/ta_qmi.te
- sepolicy/tad.te
- sepolicy/thermanager.te
- sepolicy/timekeep.te
The condition filtered out castor_windy and thus libaudioamp and liblights were not included. This resulted in non-working brightness control.
I think scorpion_windy should also be added to the list, but I don't have a device to test, so I didn't push this change.
> castor_windy, scorpion_windy: fix missing libaudioamp and liblights

- kernel-headers/uapi/linux/msm_mdp.h
- kernel-headers/uapi/video/msm_hdmi_modes.h
As subject, there were some changes in the kernel and the
headers needs to be updated.
Updated headers:
* uapi/linux/msm_mdp.h
* uapi/video/msm_hdmi_modes.h
> Update headers to reflect latest changes on 3.10 kernel

- rootdir/fstab.shinano
External sdcard is not an emulated sd.
line 69:
https://android.googlesource.com/platform/system/core/+/l-preview/fs_mgr/fs_mgr_fstab.c
> shinano: fstab: Add flag to external sd mount

- device.mk
on start of the system I can see a log saying:
E/qdhwcomposer (283): FATAL ERROR: copybit hw module not found --> avoid it building from source
> shinano: build copybit

- device.mk
needed for audio on android 6.0.0
more info: https://source.android.com/devices/audio/midi.html
> shinano: Add MIDI support

- overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
actually we are using that defined on: https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SettingsProvider/res/values/defaults.xml#56
but the correct for marshmallow is defined on device/sample: https://android.googlesource.com/device/sample/+/android-6.0.0_r1/overlays/backup/frameworks/base/packages/SettingsProvider/res/values/defaults.xml#20
> shinano: update backup service for apps

- system.prop
This reverts commit b27cb84ac13e3c547100c40ddc84ed9a8fd9540d.
see: https://android.googlesource.com/platform/hardware/qcom/media/+/android-6.0.0_r1/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp#132
Conflicts:
system.prop
> Revert "shinano: use proper black conceal color for our kernel 3.10"

- device.mk
those already defined by aosp
librs_jni --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/generic_no_telephony.mk#38
com.android.future.usb.accessory --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#35
e2fsck --> https://android.googlesource.com/platform/build/+/android-5.1.1_r24/target/product/core_minimal.mk#66
> shinano: remove double packages

- rootdir/ueventd.shinano.rc
following commit: c7c9d2bc451717c08ef151953c759a56d39025d0
> shinano: ueventd: remove deprecated camera permissions

- rootdir/init.shinano.rc
This change is part of:
https://android.googlesource.com/device/lge/hammerhead/+/38dcd1fc134a844e0e2f78b0e4e7e52a90afad79
> shinano: Remove deprecated permission

- libaudioamp/tfa9890.c
avoid warning as:
device/sony/shinano/libaudioamp/tfa9890.c: In function 'tfa9890_prepare_for_ioctl':
device/sony/shinano/libaudioamp/tfa9890.c:53:2: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
free(tfa9890_param_data.data);
^
device/sony/shinano/libaudioamp/tfa9890.c:53:2: warning: incompatible implicit declaration of built-in function 'free'
> shinano: fix header include

- device.mk
all targets (aries sirius leo castor/windy and scorpion/windy) are tracking aosp_base.mk & telephony.mk
well those are not including this: https://android.googlesource.com/platform/build/+/f29b5bd380e5ecced9bfa1d241e8b47448c29040%5E%21/#F
which let's without proper mms app on AOSP... so include it on our commons
> shinano: compile new AOSP messaging app

- rootdir/init.shinano.rc
Remove full arch path and call only lib name then the system
will preload it correctly.
> shinano: Fix dynamic linker for boringssl-compat

- sepolicy/file_contexts
- sepolicy/mlog_qmi.te
[    9.967192] init: Warning!  Service mlog_qmi_service needs a SELinux domain defined; please fix!
> shinano: SELinux: Add mlog_qmi service

- BoardConfig.mk
- sepolicy/file_contexts
- sepolicy/tfa_amp.te
[   10.893978] init: Warning!  Service tfa9890_amp needs a SELinux domain defined; please fix!
> shinano: add SELinux for TFA amp service

- rootdir/init.shinano.usb.rc
under developer options there is an option where user can choice about USB connection state one of these is charging mode only
which let's to charge the phone without enable adb services
> Shinano: Add charge only USB mode

- device.mk
The variable persist.sys.usb.config is no longer honored by the framework,
and it's presence causes unnecessary toggling of the USB driver, which
disconnects ADB and makes the device's connection unstable.
Delete it.
> shinano: Remove persist.sys.usb.config override

- overlay/frameworks/base/core/res/res/values/config.xml
this is considered all the time by aosp and without this we finish with gps not working
re-add it to make it work
https://drive.google.com/file/d/0B-e5eQvKq2t2UGs2dVlYblhlSUU/view?usp=sharing
> shinano: re-add aosp flp location provider

- BoardConfig.mk
- sepolicy/file_contexts
- sepolicy/genfs_contexts
Some files and devices are not labeled with their correct SELinux domain, which results in them being labeled with the default domain of that tree.
> Label bluetooth related files with their SELinux domain

- sepolicy/system_server.te
[  266.824989] type=1400 audit(1447450444.309:56): avc: denied { getattr } for pid=1284 comm=WifiStateMachin path=/sys/devices/platform/bcmdhd_wlan/macaddr dev=sysfs ino=12852 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
[  266.825232] type=1400 audit(1447450444.309:57): avc: denied { read } for pid=1284 comm=WifiStateMachin name=macaddr dev=sysfs ino=12852 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
[  266.825309] type=1400 audit(1447450444.309:58): avc: denied { open } for pid=1284 comm=WifiStateMachin path=/sys/devices/platform/bcmdhd_wlan/macaddr dev=sysfs ino=12852 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
Signed-off-by: David Viteri …
> shinano: add system_server policy

- sepolicy/file_contexts
it is exclusive of yukon and kanuti on aosp
https://github.com/sonyxperiadev/device-sony-yukon/blob/l-mr1/rootdir/init.yukon.rc#L365
https://github.com/sonyxperiadev/device-sony-kanuti/blob/l-mr1/rootdir/init.kanuti.rc#L393
> shinano: sepolicy: don't label wcnss_service

- BoardConfig.mk
- sepolicy/wpa.te
<38>[   21.742870] type=1400 audit(1448009566.349:11): avc: denied { getattr } for pid=1229 comm=wpa_supplicant path=/sys/devices/platform/bcmdhd_wlan/macaddr dev=sysfs ino=12852 scontext=u:r:wpa:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
<38>[   21.743124] type=1400 audit(1448009566.349:12): avc: denied { read } for pid=1229 comm=wpa_supplicant name=macaddr dev=sysfs ino=12852 scontext=u:r:wpa:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
<38>[   21.743247] type=1400 audit(1448009566.349:13): avc: denied { open } for pid=1229 comm=wpa_supplicant path=/sys/devices/platform/bcmdhd_wlan/macaddr dev=sysfs ino=12852 scontext=u:r:wpa:s0 tcontext=u:object_r:sysfs_addrsetup:s0 tclass=file permissive=1
Signed-off-by: David Viteri …
> shinano: add wpa policy

- rootdir/system/etc/media_profiles.xml
The current implementation does not support this resolution right now.
Signed-off-by: Julien Bolard <jbolard@genymobile.com>
> shinano: disable 1080p resolution on back camera to avoid crash

- sepolicy/file_contexts
- sepolicy/system_server.te
11-26 15:32:36.945  1131  1131 I Binder_3: type=1400 audit(0.0:7): avc: denied { read } for name=type dev=sysfs ino=13174 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=file permissive=1
> 11-26 15:32:36.945  1131  1131 I Binder_3: type=1400 audit(0.0:8): avc: denied { open } for path=/sys/devices/msm_dwc3/power_supply/usb/type dev=sysfs ino=13174 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=file permissive=1
> 11-26 15:32:36.945  1131  1131 I Binder_3: type=1400 audit(0.0:9): avc: denied { getattr } for path=/sys/devices/msm_dwc3/power_supply/usb/type dev=sysfs ino=13174 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=file permissive=1
>
> Signed-off-by: David Viteri <davidteri91@gmail.com>
> shinano: add policy for new USB drivers

- sepolicy/system_server.te
avoid
[   30.756958] type=1400 audit(1448553323.159:6): avc: denied { search } for pid=887 comm=ActivityManager name=usb dev=sysfs ino=13163 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=1
[   36.123415] type=1400 audit(1448553328.529:7): avc: denied { search } for pid=1644 comm=Binder_9 name=usb dev=sysfs ino=13163 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=1
[  246.138806] type=1400 audit(1448553538.058:9): avc: denied { search } for pid=1639 comm=Binder_7 name=usb dev=sysfs ino=13163 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=1
[  396.126042] type=1400 audit(1448553688.058:14): avc: denied { search } for pid=882 comm=Binder_2 name=usb dev=sysfs …
> shinano: update system_server.te

- BoardConfig.mk
Adreno requires it for BoringSSL loading.
Fixed:
dlopen failed: cannot locate symbol "BIO_f_base64"
referenced by "/system/vendor/lib/egl/libEGL_adreno.so"...
Change-Id: Ieae17bd54c63d758f18801e04e244e944f1b0883
> shinano: Add TARGET_REQUIRES_B64_COMPAT

- sepolicy/file_contexts
set bluesleep files as sysfs_bluetooth_writable
Fix:
[   36.115517] type=1400 audit(1450813677.282:254): avc: denied { write } for pid=2613 comm=626C756564726F69642077616B652F name="lpm" dev="proc" ino=4026544871 scontext=u:r:bluetooth:s0 tcontext=u:object_r:proc:s0 tclass=file permissive=1
Change-Id: I3894df4143447835de6df6a40efebef4621c2f2a
> shinano: sepolicy: Fix bluetooth denials

- device.mk
- overlay/frameworks/base/core/res/res/values/config.xml
- power/Android.mk
- power/power.c
- rootdir/init.shinano.rc
We dropped the QCOM PowerHAL because it relies on too many
proprietary blobs. Instead we have a kernel solution, but
several features still depend on the presence of a PowerHAL,
so Android is actually not happy about it.
Marshmallow introduced native double-tap-to-wake support,
which is built into the PowerHAL. This commit enables DTTW
and adds a very simple PowerHAL to support this feature.
Hopefully we can later extend this when our kernel driver
can accept changes from userspace.
> Add a simple PowerHAL for native double-tap-to-wake

- rootdir/init.shinano.pwr.rc
Many other custom ROMs set this automatically
> PowerHAL: AOSP does not set the governor perms

- sepolicy/system_app.te
Avoid
[  652.214267] type=1400 audit(1452457241.198:14): avc: granted { add_name } for pid=6019 comm=system:ui name=cache scontext=u:r:system_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir
[  652.235670] type=1400 audit(1452457241.198:15): avc: granted { create } for pid=6019 comm=system:ui name=cache scontext=u:r:system_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir
[  652.261785] type=1400 audit(1452457241.198:16): avc: granted { setattr } for pid=6019 comm=system:ui name=cache dev=mmcblk0p25 ino=390970 scontext=u:r:system_app:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir
> shinano: add policy for more denials

- device.mk
those are defined at qcom-vendor.mk in vendor files
> shinano: remove vendor products

- rootdir/fstab.shinano
> [Shinano] fstab: Fix USB OTG XHCI path for USB HDD mount

- sepolicy/init.te
Avoid
01-13 09:27:31.610 I/toolbox (4126): type=1400 audit(0.0:31): avc: denied { getattr } for path=/dev/mtp_usb dev=tmpfs ino=8001 scontext=u:r:init:s0 tcontext=u:object_r:mtp_device:s0 tclass=chr_file permissive=1
> shinano: update init.te

- device.mk
> shinano: Move NFC HAL build name to device

- sepolicy/file_contexts
- sepolicy/mediaserver.te
Avoid
22.277835] type=1400 audit(1453397071.649:11): avc: denied { write } for pid=310 comm=mediaserver name=delta dev=mmcblk0p25 ino=390981 scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.277928] type=1400 audit(1453397071.649:12): avc: denied { add_name } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   22.278041] type=1400 audit(1453397071.649:13): avc: denied { create } for pid=310 comm=mediaserver name=Bluetooth_cal.acdbdelta scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   22.278129] type=1400 audit(1453397071.649:14): avc: denied { open } for pid=310 comm=mediaserver …
> shinano: SELinux for acdb files

- rootdir/init.shinano.rc
readahead values:
https://github.com/sonyxperiadev/kernel/commit/02246eebb459560296a163529f22ffb724ccaa30
Change-Id: I521e628c5efcd53fa85eaa27ae2dbdc4a27f9dbb
> shinano: init: Use predefined readahead values from kernel

- power/power.c
BUG on aosp:
Enable Saver mode ... after that you can't disable it anymore causing reboots also if you connect usb it causes reboots too
Thanks @kholk
> shinano: powerhal: fix saver mode on/off

- rootdir/system/etc/audio_effects.conf
not using
pre_processing {
voice_communication {
aec {
}
ns {
}
}
}
it is specific for hammerhead
> shinano: use hammerhead's audio_effects

- rootdir/system/etc/media_profiles.xml
this fixes 480p mode (green artifacts)
the row is now
1080p (disabled) 1920*1080 - timelapse1080p 1920*1088
720p (enabled)  1280* 720 - timelapse 720p 1280* 720
480p (enabled)   640* 480 - timelapse 480p  720* 480
CIF (enabled)   352* 288 - timelapse  CIF  352* 288
those values were calculated with: http://developer.android.com/reference/android/media/CamcorderProfile.html
the fix for 480p mode, you can see it here: http://developer.android.com/reference/android/media/CamcorderProfile.html#QUALITY_480P
> shinano: update media_profiles

- rootdir/fstab.shinano
to handle the different paths for wifi and sdcard between scorpion and
other shinano devices, add all msm_sdcc using the wildcard and let fstab
check for existence
> fstab: fix external storage path

- rootdir/init.recovery.shinano.rc
It is required for partitions mounting process.
Change-Id: I6a8123e6a818c98ea51b0f22574cc70aef585fa3
> shinano: recovery: Add /dev/block/bootdevice symlink

- rootdir/init.recovery.shinano.rc
this is the correct path for shinano devices.
Change-Id: I78d57efb474425bc3ea0c19276b8ff885b656993
> shinano: recovery: Fix block path

- rootdir/init.shinano.rc
HAL is hardwired to look at pn544
> NFC: Add back lost symlink

- rootdir/ueventd.shinano.rc
Since lights HAL is unified then all platforms
should be set this permission for system.
Change-Id: I1d4e3d6b43a44217a016b877c9686eebdac91ef2
> shinano: ueventd: Add common lights sysfs path

- libaudioamp/tfa9890.c
A fixed-length array of unsigned char can never be NULL!
Fix the logic by initializing the array correctly and assigning
to the param struct if we copied anything with memcpy into it
instead of doing an useless null check.
> [SHINANO] libaudioamp: tfa9890: Fix logic mistake in ioctl for eq function

- rootdir/init.shinano.pwr.rc
- rootdir/ueventd.shinano.rc
05-14 21:01:24.493   842   863 E Simple PowerHAL: Error opening /sys/devices/system/cpu/cpuquiet/rqbalance/balance_level: Permission denied
05-14 21:01:24.494   842   863 E Simple PowerHAL: Error opening /sys/devices/system/cpu/cpuquiet/rqbalance/nr_run_thresholds: Permission denied
05-14 21:01:24.494   842   863 E Simple PowerHAL: Error opening /sys/devices/system/cpu/cpuquiet/rqbalance/nr_down_run_thresholds: Permission denied
Change-Id: I8ed5f09c407776a5d8fd7984c0d68a216b431614
> shinano: Fix rqbalance permissions

- rootdir/init.shinano.pwr.rc
- rootdir/ueventd.shinano.rc
Fix and move simple power HAL permissions to "on init" stage
then it will also be able early to LPM mode.
Change-Id: Ibc882eaaca0dc7431f9ca722e879a0091c16bdfe
> shinano: Fix simple power HAL permissions

- PlatformConfig.mk
They have been hrmless up to Marshmallow but now they cause conflicts:
out/soong/make_vars-aosp_d6503.mk:202: TARGET_GLOBAL_CFLAGS does not match between Make and Soong:
out/soong/make_vars-aosp_d6503.mk:202: Make  adds:
out/soong/make_vars-aosp_d6503.mk:202: Soong adds: -DANDROID -DNDEBUG -D_FORTIFY_SOURCE=2 -D__ARM_FEATURE_LPAE=1 -UDEBUG -W -Wa,--noexecstack -Wall -Werror=address -Werror=date-time -Werror=format-security -Werror=non-virtual-dtor -Werror=return-type -Werror=sequence-point -Winit-self -Wno-multichar -Wno-unused -Wpointer-arith -Wstrict-aliasing=2 -fdata-sections -fdebug-prefix-map=/proc/self/cwd= -fdiagnostics-color -ffunction-sections -fgcse-after-reload -fmessage-length=0 -fno-builtin-sin -fno-canonical-system-headers -fno-exceptions -fno-short-enums …
> Remove obsolete global flags

- platform.mk
As discussed, it is not needed, and doesnt work anyway, as spaces in
overrides do not work and results into the build.prop entry being:
rild.libargs=-d
/dev/smd0
> shinano: remove rild.libargs

- PlatformConfig.mk
- rootdir/init.shinano.pwr.rc
- rootdir/ueventd.shinano.rc
- system.prop
Core limiting via msm_performance works well, but cpuquiet absolutely
hates it. rqbalance is not aware of msm_performance so it spams dmesg
because it cannot online a core for 'unknown' reasons.
We can achieve the same result using cpuquiet which rqbalance is
aware of. We can also have two sources of core limiting, power
profile and thermal.
We also need to tune rqbalance and cpuquiet per platform so also
move their system props.
> Move sysfs and props for cpuquiet hotplugging

- bluetooth/bdroid_buildcfg.h
Use ro.boot.hardware property and naming BT dynamically.
Change-Id: Iff4f4dd51a2ad5588e35c14dbf70b63e1d69a940
> [master] sony: shinano: Set BT default name dynamically

- bluetooth/bdroid_buildcfg.h
Use ro.boot.hardware property for BT device name.
> [m-mr1] sony: shinano: Set BT default name dynamically

- system.prop
Tune rqbalance to linearize CPU hotplugging and	optimize power
consumption while retaining performance.
> [SHINANO] system.prop: Tune rqbalance parameters

- rootdir/fstab.shinano
Android Nougat changed how it communicates with the recovery
partition. Until now the recovery commands had been written
to the /cache partition, but this has changed. Now recovery
writes to the /misc partition.
Fortunately for shinano devices we actually have
an empty and unused /apps_log partition we can use.
> fstab: Allow recovery to use the misc partition

- rootdir/init.shinano.rc
Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.
> macaddr: remove dangerous sepolicy permissions

- rootdir/init.shinano.rc
If the fix is not present, the device will kill macaddrsetup and you will get a new bluetooth and wlan mac adress every time you reboot
> Fix Bluetooth MAC-Adress read from /data/misc

- rootdir/init.shinano.rc
Reverts sonyxperiadev/device-sony-shinano#314
the folder had bluetooth permissions and this change is noy needed
> Revert "Fix Bluetooth MAC-Adress read from /data/misc"

- rootdir/system/etc/bluetooth/bt_vendor.conf
- rootdir/ueventd.shinano.rc
Those patches are logically required for BRCM BT FM.
We need to test them on all devices first.
> BRCM BT FM

- rootdir/init.shinano.rc
It is required for sepolicy.
Change-Id: I47fbc7d6d20ec89a38402f639d2fdf18639bb833
> sony: shinano: init: Label UIM service

- PlatformConfig.mk
- platform.mk
* Avoid hardcoding the paths by using common
variables declared once for path accesses
Change-Id: I81226a249c6258360c540c80ae4dfe5073439921
Signed-off-by: Adrian DC <radian.dc@gmail.com>
> shinano: config: Use unique variables for device paths

- PlatformConfig.mk
following marling config https://android.googlesource.com/device/google/marlin/+/android-7.1.1_r8/marlin/BoardConfig.mk#200
> shinano: use correct flag nfc for android-7.1.1

- bluetooth/bdroid_buildcfg.h
- rootdir/system/etc/bluetooth/bt_vendor.conf
Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.
> [WIP - n-mr1] BT/FMRadio using the broadcom ldisc driver

- bluetooth/bdroid_buildcfg.h
- rootdir/system/etc/bluetooth/bt_vendor.conf
Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.
> [WIP - n-mr0] BT/FMRadio using the broadcom ldisc driver

- bluetooth/bdroid_buildcfg.h
- rootdir/system/etc/bluetooth/bt_vendor.conf
Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.
> [WIP - m-mr1] BT/FMRadio using the broadcom ldisc driver

- bluetooth/bdroid_buildcfg.h
Move HCILP_INCLUDED out of OS_GENERIC #ifdef .
OS_GENERIC flag was used to fix BTDefaultName at Nougat.
Change-Id: I18d9140d85e85c794a3db4f3605fe0950c13cfdf
> sony: shinano: Move BT flag

- PlatformConfig.mk
- sepolicy_platform/file_contexts
We have	removed	the dev	block nodes from the common repository
device-sony-sepolicy's file_contexts because it was really
getting too much dirty.... and also, now that UFS has appeared
we had a conflict: on those devices, mmcblk0 is	SDCard,	while
on eMMC	devices	it is the eMMC.
This file_contexts contains only the correct and necessary
block node contexts for	this platform.
> Add platform-specific file_contexts

- rootdir/init.shinano.rc
Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I645d22e899735415cc15c821042c4df3b0f169a4
> sony: shinano: Increase max number of compression streams
