rootdir/init.shinano.pwr.rc, rootdir/init.shinano.rc
this commit also improve boot time and remove old cruft
=> udpate power management sysfs path

device.mk, kernel-headers/sound/audio_effects.h, kernel-headers/sound/compress_offload.h, kernel-headers/sound/compress_params.h, rootdir/system/etc/audio_effects.conf
this contains i. e. hw equalizer and offload support
=> audio: copy audio effects from hammerhead

overlay/frameworks/base/core/res/res/values/config.xml, overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml, overlay/frameworks/base/packages/SystemUI/res/values/defaults.xml
Values taken from factory images, nexus configs and our other AOSP configs
=> shinano: properly configure overlays

overlay/packages/services/Telephony/res/values/config.xml, system.prop
=> shinano: Enable LTE

overlay/frameworks/base/core/res/res/values/config.xml
Product Package is compiled for a while: https://github.com/sonyxperiadev/device-sony-shinano/blob/master/device.mk#L79
=> shinano: enable miracast bool support

rootdir/init.shinano.rc
https://github.com/android/platform_system_core/commit/5c3c77ed7855d262645c44b7e239476d9b66393d
=> init.shinano.rc: Remove WiFi directory creation

overlay/packages/inputmethods/LatinIME/java/res/values/gesture-input.xml, rootdir/init.shinano.rc, rootdir/system/etc/mixer_paths.xml
=> shinano: LatinIME: enable input gesture

rootdir/ueventd.shinano.rc
introduced in commit: f3f32481cf3b30715bebec40726bd870b6af6a8c
=> shinano: fix permission for video node

device.mk
Barometer
Present on:
Leo Sony Stock 23.1.A.1.28
Sirius Sony Stock 23.1.A.1.28
Aries Sony Stock 23.1.A.1.28
=> shinano: add missing sensor permission

device.mk
those are defined in default.prop
=> shinano: remove duplicate art props

BoardConfig.mk, README.md, device.mk, libaudioamp/Android.mk, liblights/lights.c, overlay/frameworks/base/packages/SystemUI/res/values/config.xml, rootdir/fstab.shinano, rootdir/init.shinano.pwr.rc, rootdir/init.shinano.rc, system.prop
=> shinano: Sources cleanup

device.mk
Remove old and deprecated packages
=> shinano: Package cleanup

rootdir/ueventd.shinano.rc
following commit: 7b7eda9f3f2fa66bde55fffa13263a56099b669b
=> shinano: ueventd: remove deprecated camera permissions

device.mk
Bug: 20658562
Change-Id: Ib8e47b3edd94b1977c294959cdde01a54b64f123
Signed-off-by: Thierry Strudel <tstrudel@google.com>
=> shinano: Force dex2oat not to use swap file

rootdir/fstab.shinano
more info: https://source.android.com/devices/storage/adoptable.html & https://source.android.com/devices/storage/config.html#android_6_0
=> shinano: adoptable MicroSD

rootdir/system/etc/media_profiles.xml
following nexus configuration for M
=> shinano: remove video editor from media_profiles

device.mk
Enable MultiWindow as described here:
http://forum.xda-developers.com/showpost.php?p=63230682&postcount=85
=> shinano: enable MultiWindow

BoardConfig.mk
=> shinano: define nfc chip type for new implementation

overlay/frameworks/base/core/res/res/values/config.xml
Used by Google Play Services if available
=> shinano: let us use Google Provider for gps

rootdir/init.shinano.pwr.rc, rootdir/init.shinano.rc
=> shinano: Move power stuff to pwr.rc

BoardConfig.mk, sepolicy/file_contexts
add mlog_qmi.te to BOARD_SEPOLICY_UNION (see commit: 9c1623709b8b5d13727b780f69cbba83f8d8945f)
also update nfc generic driver pn54x
=> shinano: update SELinux

overlay/frameworks/base/core/res/res/values/config.xml
more info: https://github.com/android/platform_frameworks_base/commit/8c621ef54630e411d50e9ba1d8d8ed19ef93f9e1
=> shinano: Add support for static RadioCapabilities

BoardConfig.mk
=> shinano: Remove deprecated BOARD_NFC_HAL_SUFFIX

rootdir/init.shinano.rc, sepolicy/bluetooth.te, sepolicy/file_contexts
solved
[    9.597272] init: property_set("ro.bt.bdaddr_path", "/data/etc/bluetooth_bdaddr") failed
and all problems related to it
=> Fixed from L branch

device.mk, rootdir/system/etc/media_codecs.xml, rootdir/system/etc/media_codecs_performance.xml
=> shinano: use hammerhead's media_codecs

device.mk
=> shinano: Add new camera2 hardware features

sepolicy/file_contexts
=> sepolicy: Remove duplicate entry for tad_static

sepolicy/file_contexts
This reverts commit f944cac049c78f312a2bfcfa10efe71eece6c866.
=> Revert "sepolicy: Remove duplicate entry for tad_static"

power/power.c
When the device is asleep we don't need to scale up the cpu
frequencies so we can tune the governor to make it twice as hard
to scale up and twice as easy to scale down.
We do this by adding profiles. the 'power saving' profile can
be used when the device is asleep, or when Android enters a low
power mode. This profile also lowers the 'hispeed' from 1190MHz
to 960MHz.
The PowerHAL can also briefly boost frequencies to the 'hispeed'
frequency when the user interacts with the device. The boost is
only for 80ms but this dramatically improves responsiveness,
including 20% quicker wake from sleep.
=> power: add some PowerHAL enhancements

power/power.c, power/power.h, rootdir/init.shinano.pwr.rc
Now it is more robust, easier to extend
=> PowerHAL refactor

sepolicy/file_contexts
=> shinano: selabel recovery partition

rootdir/init.shinano.rc
add ril-daemon2 service needed by Dual Sim devices
Signed-off-by: Alin Jerpelea <alin.jerpelea@sonymobile.com>
=> add dsds service

kernel-headers/linux/pn547.h, kernel-headers/sound/compress_params.h
reflect current LA.BF64.1.2.2_rb4.7 kernelheaders
Testbuild succeeded on Leo
=> shinano: update kernelheaders

rootdir/fstab.shinano
Follow M way also update otg path from this commit: 15aff975fb2941f78d4438173d9c71ce515b0e36
https://drive.google.com/file/d/0B-e5eQvKq2t2eFEyMUxRQUlyUk0/view
Signed-off-by: Angelo G. Del Regno <kholk11@gmail.com>
=> shinano: update fstab

device.mk
introduce on big cleanup to sony-common
=> shinano: fix typo

BoardConfig.mk, device.mk
adds unified includes to family .mk
=> clean inclusion

rootdir/ueventd.shinano.rc
=> shinano: add permissions for hw effects

rootdir/init.shinano.rc, system.prop
Krait cores are powerful like the big cores in msm8994 so we shoud
be conserviative about bringing these cores online.
=> cpuquiet: tune hotplugging for shinano platform

rootdir/fstab.shinano, rootdir/init.shinano.rc
This can give a nice performance boost under heavy load
=> Configure Zram on shinano devices

rootdir/init.shinano.rc
Following kitakami: https://github.com/sonyxperiadev/device-sony-kitakami/commit/f945af43f8e70edb46f20b33dcae0ec10e6249da
=> shinano: Add support for top-app cpuset

PlatformConfig.mk
7.1.1_r4 requirement
https://android.googlesource.com/platform/external/libnfc-nci/+/android-7.1.1_r4/halimpl/pn54x/Android.mk#15
Change-Id: I7d29137c6afe165ce7814aa61d957a83414152e8
=> [master] sony: shinano: Update NFC chip type config

PlatformConfig.mk, platform.mk
Needed patches
https://android-review.googlesource.com/#/q/topic:sony-hal1+(status:open+OR+status:merged)
=> shinano: enable legacy camera fixes

PlatformConfig.mk
This reverts commit 3f8e7d6301e45c75776014a0740c85039f65da3d.
=> Revert "sony: shinano: Update NFC chip type config"

rootdir/ueventd.shinano.rc
also removed not present paths
=> shinano: ueventd: fix nfc permissions

PlatformConfig.mk
Add kernel version in order to select HAL version included in commit:
https://github.com/sonyxperiadev/device-sony-common/commit/97b15e6c13853ab9abfdd8ceac51af52d437b5d7
=> Add TARGET_KERNEL_VERSION := 3.10
